services:
  postgres:
    image: postgres:15-alpine
    container_name: formist_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d formist_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - golang:1.24-alpine
    container_name: formist_admin
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/formist_db?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: